Cannot find module './SessionContainer' fix
Filename is `sessionContainer`, so we should require `sessionContainer`, but not `SessionContainer`.
Requiring `SessionContainer` results in `Error: Cannot find module './SessionContainer'` (tested on linux)